/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package filmclub.view;

import filmclub.controller.ActorsController;
import filmclub.controller.FilmsController;
import filmclub.dao.ActorDAOHibernate;
import filmclub.dao.FilmDAOHibernate;
import filmclub.dao.LanguageDAOHibernate;
import hibernate.HibernateUtil;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import org.hibernate.HibernateException;

/**
 *
 * @author gabag
 */
public class FilmClubHome extends javax.swing.JFrame {

    /**
     * Creates new form FilmClubHome
     */
    public FilmClubHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        fileExitMenuItem = new javax.swing.JMenuItem();
        filmsMenu = new javax.swing.JMenu();
        filmsListMenuItem = new javax.swing.JMenuItem();
        actorsMenu = new javax.swing.JMenu();
        actorsListMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FilmClub");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        homePanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/filmClubLogo.png"))); // NOI18N
        jLabel1.setToolTipText("");
        homePanel.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(homePanel, java.awt.BorderLayout.CENTER);

        fileMenu.setText("File");

        fileExitMenuItem.setText("Exit");
        fileExitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileExitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(fileExitMenuItem);

        menuBar.add(fileMenu);

        filmsMenu.setText("Films");

        filmsListMenuItem.setText("Film list");
        filmsListMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filmsListMenuItemActionPerformed(evt);
            }
        });
        filmsMenu.add(filmsListMenuItem);

        menuBar.add(filmsMenu);

        actorsMenu.setText("Actors");

        actorsListMenuItem.setText("Actor list");
        actorsListMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actorsListMenuItemActionPerformed(evt);
            }
        });
        actorsMenu.add(actorsListMenuItem);

        menuBar.add(actorsMenu);

        setJMenuBar(menuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private boolean isHibernateConnected() {
        
        try {
            HibernateUtil.getSessionFactory().openSession();
        } catch (ExceptionInInitializerError | HibernateException ex) {
            return false;
        }
        
        return true;
    }
    
    private void fileExitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileExitMenuItemActionPerformed
        // TODO add your handling code here:
        
        int result = JOptionPane.showOptionDialog(this, 
                "Are you sure you want to exit?", "Exit FilmClub", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, 
                null, null);
        
        if (result == JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_fileExitMenuItemActionPerformed

    private void actorsListMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actorsListMenuItemActionPerformed
        // TODO add your handling code here:
        
        if (isHibernateConnected()) {
            FilmClubActors filmClubActors = FilmClubActors.getInstance();

            if (filmClubActors.getController() == null) {
                ActorsController controller = new ActorsController(new ActorDAOHibernate());

                filmClubActors.setController(controller);
                controller.setObserver(filmClubActors);
                controller.findAll();
            }

            filmClubActors.setVisible(true);
        }
        else {
            JOptionPane.showMessageDialog(this, "Can't connect to MySQL server. "
                    + "This application needs access to a MySQL sakila database.", 
                    "Connection error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_actorsListMenuItemActionPerformed

    private void filmsListMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filmsListMenuItemActionPerformed
        // TODO add your handling code here:
        
        if (isHibernateConnected()) {
            FilmClubFilms filmClubFilms = FilmClubFilms.getInstance();
        
            if (filmClubFilms.getController() == null) {
                FilmsController controller = new FilmsController(new FilmDAOHibernate(), new LanguageDAOHibernate());

                filmClubFilms.setController(controller);
                controller.setObserver(filmClubFilms);
                controller.findAll();
            }

            filmClubFilms.setVisible(true);
        }
        else {
            JOptionPane.showMessageDialog(this, "Can't connect to MySQL server. "
                    + "This application needs access to a MySQL sakila database.", 
                    "Connection error", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_filmsListMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilmClubHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilmClubHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilmClubHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilmClubHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilmClubHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem actorsListMenuItem;
    private javax.swing.JMenu actorsMenu;
    private javax.swing.JMenuItem fileExitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem filmsListMenuItem;
    private javax.swing.JMenu filmsMenu;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
